version: '3'

services:
  pg-master:
    container_name: "${COMPOSE_PROJECT_NAME:-pg}-master"
    image: dmed/riwaq-pg-realtime-postgres
    ports: ["${PG_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "log_min_messages=fatal"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  pg-worker:
    image: dmed/riwaq-pg-realtime-postgres
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  pg-manager:
    container_name: "${COMPOSE_PROJECT_NAME:-pg}-manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH

  riwaq-pg:
    image: dmed/riwaq-pg-server
    container_name: riwaq-pg
    environment:
      DATABASE_URL: postgres://postgres:change-me@postgres:2345/postgres
      DB_SCHEMA: public
      JWKS_URI: https://auth.mahd.cloud/oauth/v2/keys
    ports:
      - "5000:5000"
    depends_on:
      - postgres
volumes:
  postgres-data:
