version: '3'

services:
  postgres:
    image: dmed/riwaq-pg-realtime-postgres
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "2345:5432"

  riwaq-pg:
    image: dmed/riwaq-pg-server
    container_name: riwaq-pg
    environment:
      DATABASE_URL: postgres://postgres:change-me@postgres:2345/postgres
      DB_SCHEMA: public
      JWKS_URI: https://auth.mahd.cloud/oauth/v2/keys
    ports:
      - "5000:5000"
    depends_on:
      - postgres
volumes:
  postgres-data:
